import { useQuery } from "@tanstack/react-query";
import { FilePlus2, FolderOpen, LockKeyhole, Upload } from "lucide-react";
import { type ChangeEvent, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../../api/client";
import { InvestorIdentityRail } from "../rehearsal/InvestorIdentityRail";
import "../rehearsal/intake.css";
import "./projects.css";

export function AssessPitchChooser(){
 const {vcSlug=""}=useParams();const navigate=useNavigate();const profile=useQuery({queryKey:["profile",vcSlug],queryFn:()=>api.profile(vcSlug)});const projects=useQuery({queryKey:["projects"],queryFn:api.projects});
 const [mode,setMode]=useState<"existing"|"new">("existing");const [projectId,setProjectId]=useState("");const [versionId,setVersionId]=useState("");const [company,setCompany]=useState("");const [pitch,setPitch]=useState("");const [authorized,setAuthorized]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const projectDetail=useQuery({queryKey:["project",projectId],queryFn:()=>api.project(projectId),enabled:Boolean(projectId)});const chosenVersion=versionId||projectDetail.data?.current_version_id||"";const canAssess=mode==="existing"?Boolean(projectId&&chosenVersion):Boolean(company.trim()&&pitch.trim());
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!/\.(txt|md)$/i.test(file.name)){setError("Upload a UTF-8 .txt or .md file.");return}const text=(await file.text()).replace(/\r\n?/g,"\n");if(text.length>200000){setError("Pitch exceeds the 200,000 character limit.");return}setPitch(text);setError("")}
 async function create(assess:boolean){setBusy(true);setError("");try{const project=await api.createProject({display_name:company.split(",")[0].trim(),company_aliases:company.split(",").map(value=>value.trim()).filter(Boolean),pitch_text:pitch});if(assess)await api.startAssessment(project.project_id,project.current_version_id,vcSlug,profile.data?.investor.investor_version_id);navigate(`/pitches/${project.project_id}/versions/${project.current_version_id}${assess?"?tab=assessments":""}`)}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save pitch");setBusy(false)}}
 async function assessExisting(){if(!projectId||!chosenVersion)return;setBusy(true);setError("");try{await api.startAssessment(projectId,chosenVersion,vcSlug,profile.data?.investor.investor_version_id);navigate(`/pitches/${projectId}/versions/${chosenVersion}?tab=assessments`)}catch(caught){setError(caught instanceof Error?caught.message:"Unable to start assessment");setBusy(false)}}
 return <section className="assess-chooser"><header><h1>Assess your pitch</h1><p>Start from a pitch you have already saved, or create a new immutable pitch version. Saving alone does not call the model provider.</p></header><div className="assess-layout">{profile.data?.investor?<InvestorIdentityRail investor={profile.data.investor}/>:<aside className="identity-rail loading">Loading investor profile…</aside>}<div className="assess-panel"><div className="assess-paths" role="tablist" aria-label="Pitch source"><button role="tab" aria-selected={mode==="existing"} onClick={()=>setMode("existing")}><FolderOpen/><span><strong>Use a saved pitch</strong><small>Choose an immutable version you already created.</small></span></button><button role="tab" aria-selected={mode==="new"} onClick={()=>setMode("new")}><FilePlus2/><span><strong>Create a new pitch</strong><small>Save first, then assess now or later.</small></span></button></div>
  {mode==="existing"?<section className="existing-pitch-choice"><h2>Choose a saved pitch</h2>{projects.isPending?<p>Loading your pitch library…</p>:!projects.data?.projects.length?<div className="assessment-empty"><p>You have no saved pitches yet.</p><button onClick={()=>setMode("new")}>Create your first pitch</button></div>:<><label>Pitch project<select value={projectId} onChange={event=>{setProjectId(event.target.value);setVersionId("")}}><option value="">Select a pitch</option>{projects.data.projects.map(row=><option key={row.project_id} value={row.project_id}>{row.display_name} · {row.version_count} version{row.version_count===1?"":"s"}</option>)}</select></label>{projectDetail.data&&<label>Pitch version<select value={chosenVersion} onChange={event=>setVersionId(event.target.value)}>{projectDetail.data.versions.map((row,index)=><option key={row.version_id} value={row.version_id}>Version {index+1} · {new Date(row.created_at).toLocaleDateString()}</option>)}</select></label>}</>}</section>:<section className="new-pitch-choice"><h2>Create a new pitch</h2><label>Company name or aliases<input value={company} onChange={event=>setCompany(event.target.value)} placeholder="Acme, Acme AI"/></label><label>Pitch text<textarea value={pitch} onChange={event=>setPitch(event.target.value.slice(0,200000))} rows={15} placeholder="Paste the pitch exactly as the investor would receive it…"/></label><div className="project-upload"><label htmlFor="assess-pitch-file"><Upload size={15}/> Upload .txt or .md</label><input id="assess-pitch-file" type="file" accept=".txt,.md,text/plain,text/markdown" onChange={upload}/><span>{pitch.length.toLocaleString()} / 200,000 characters</span></div></section>}
  {profile.error&&<p className="error" role="alert">{profile.error.message}</p>}{profile.data&&!profile.data.investor.start_available&&<p role="status">This investor is not available for new assessments. Choose a ready version in Settings.</p>}{error&&<p className="error" role="alert">{error}</p>}{canAssess&&<label className="match-authorization"><input type="checkbox" checked={authorized} onChange={event=>setAuthorized(event.target.checked)} aria-label="Authorize provider API costs"/><span>Authorize provider API costs for this canonical assessment.</span></label>}<div className="assess-actions">{mode==="new"&&<button className="button secondary" disabled={busy||!company.trim()||!pitch.trim()} onClick={()=>create(false)}>Save pitch only</button>}<button className="button" disabled={busy||!canAssess||!authorized||!profile.data?.investor.start_available} onClick={()=>mode==="existing"?assessExisting():create(true)}>{busy?"Starting assessment…":mode==="new"?"Save and assess":"Assess selected pitch"}</button></div><p className="assess-privacy"><LockKeyhole size={15}/> Credentials, prompts, and raw provider responses are not exposed.</p>
 </div></div></section>
}
