import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowRight, LoaderCircle, RotateCcw } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../../api/client";
import type { Investor, InvestorMatch, RehearsalDepth } from "../../api/types";
import { AssessmentMetricHelp, fitScore } from "../../components/AssessmentSemantics";

const title=(value:string)=>value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const ordinal=(value:number)=>{const rounded=Math.round(value);const mod100=rounded%100;const suffix=mod100>=11&&mod100<=13?"th":rounded%10===1?"st":rounded%10===2?"nd":rounded%10===3?"rd":"th";return `${rounded}${suffix}`};

export function MatchResults({match:initial,investors}:{match:InvestorMatch;investors:Investor[]}){
 const navigate=useNavigate();const client=useQueryClient();
 const query=useQuery({queryKey:["match",initial.match_id],queryFn:()=>api.match(initial.match_id),initialData:initial,refetchInterval:q=>["queued","running"].includes(q.state.data?.status||"")?1500:false});
 const retry=useMutation({mutationFn:(slug:string)=>api.retryMatch(initial.match_id,slug),onSuccess:data=>client.setQueryData(["match",initial.match_id],data)});
 const rehearse=useMutation({mutationFn:({id,depth}:{id:string;depth:RehearsalDepth})=>api.startAssessmentRehearsal(id,depth),onSuccess:job=>navigate(`/sessions/${job.session_id}`)});
 const bySlug=new Map(investors.map(row=>[row.vc_slug,row]));const match=query.data;
 return <section className="match-results" aria-label="Investor match results"><header><div><h2>Investor shortlist</h2><p>Compare each investor-like model against its own historical record. Estimated fit scores are not endorsements or comparable real-world investment probabilities.</p></div><span className={`match-status ${match.status}`}>{match.status}</span></header><ol>{match.assessments.map(row=>{const investor=bySlug.get(row.vc_slug);return <li key={row.assessment_id} className={`match-row ${row.status}`}><div className="match-rank">{row.highest_estimated_fit?<strong>{row.relative_fit.percentile==null?"Highest estimated fit":"Highest historical fit"}</strong>:row.leading_group?<strong>{row.relative_fit.percentile==null?"Leading group":"Leading historical-fit group"}</strong>:<span>{row.status}</span>}</div><div className="match-identity">{investor?.portrait_path&&<img src={investor.portrait_path} alt=""/>}<div><h3>{investor?.display_name||row.vc_slug}</h3><p>{investor?.firm}</p></div></div>{row.status==="complete"?<><dl className="match-metrics"><div className="historical-fit"><dt>Historical fit percentile</dt><dd>{row.relative_fit.percentile==null?"Unavailable":`${ordinal(row.relative_fit.percentile)} percentile`}</dd><small>{row.relative_fit.reference_count} historical pitches</small><AssessmentMetricHelp kind="percentile"/></div><div><dt>Estimated investor fit</dt><dd>{fitScore(row.investment_likelihood)==null?"Unavailable":`${fitScore(row.investment_likelihood)}/100`}</dd><AssessmentMetricHelp kind="fit"/></div><div><dt>Assessment confidence</dt><dd>{fitScore(row.decision_confidence)==null?"Unavailable":`${fitScore(row.decision_confidence)}%`}</dd><AssessmentMetricHelp kind="confidence"/></div></dl><div className="match-rationales"><span>{row.positive_rationales.slice(0,2).map(title).join(" · ")||"No strong positive rationale identified"}</span><span>{row.negative_rationales.slice(0,2).map(title).join(" · ")||"No strong concern identified"}</span></div><div className="match-actions"><Link to={`/pitches/${match.project_id}/versions/${match.version_id}?tab=assessments`}>View assessment</Link><button className="button secondary" onClick={()=>rehearse.mutate({id:row.assessment_id,depth:"standard"})}>Start rehearsal <ArrowRight size={14}/></button></div></>:row.status==="failed"?<div className="match-failure" role="alert"><AlertTriangle size={16}/><span>{row.public_error||"Assessment did not complete."}</span><button onClick={()=>retry.mutate(row.vc_slug)}><RotateCcw size={14}/> Retry</button></div>:<div className="match-working" role="status"><LoaderCircle size={16}/><span><strong>Building the investor-like assessment</strong><small>Reviewing the pitch, retrieving relevant investor evidence, and synthesizing the rationale profile.</small></span></div>}</li>})}</ol></section>
}
